"""User-provided generator banks."""

INSTRUCTIONS = [
    "Always stand close to another player",
    "Backstab other characters",
    "Be easily influenced by others",
    "Delegate all actions",
    "Die very very slowly",
    "Discover that you are colorblind",
    "If 2 other characters are present, always keep an equal distance to them",
    "Introduce several new locations",
    "Make a confession halfway the scene",
    "Only speak after you made a small movement",
    "Sit down as much as possible",
    "Speak only in short sentences",
    "Stay close to walls",
    "Think before you say something",
    "Use many difficult words",
    "You want to be in the highest physical position",
    "Start the scene while in the middle of an action",
    "You like each character, despite what they say",
    "Always keep some distance from other players",
    "Find an excuse to lay down on the ground",
    "Only speak if you touch another player",
    "Whenever there is a silence, you start humming",
    "Start every scene singing",
    "Start each conversation with a complement",
    "Fall in love with each other persona that you meet",
]

EMOTIONS = [
    "Adoration", "Agitated", "Alert", "Angry", "Annoyed", "Anxious", "Apathy", "Bored",
    "Brazen", "Calm", "Compassion", "Confident", "Confused", "Courageous", "Crazy", "Curious",
    "Defensive", "Depressed", "Destructive", "Determined", "Disappointed", "Disgust", "Dominant",
    "Doubting", "Dramatic", "Enlightened", "Enthusiasm", "Envious", "Excited", "Friendly",
    "Gloomy", "Gratitude", "Grumpy", "Happy", "Hopeless", "Hostile", "Hurt", "In awe",
    "Insecure", "Insightful", "Intrigued", "Invincible", "Irritated", "Jealous", "Loony",
    "Lost", "Mad", "Melodramatic", "Miserable", "Misunderstood", "Nervous", "Passion", "Pride",
    "Protective", "Proud", "Relaxed", "Relief", "Resentful", "Sad", "Sensitive", "Serenity",
    "Stressed", "Strong", "Surprised", "Suspicious", "Sympathy", "Troubled", "Unstable",
]

ACTIONS = [
    "Building a house", "Catching a thief", "Changing an outfit", "Cleaning the house",
    "Climbing a mountain", "Closing the curtains", "Cooking a meal", "Cutting down a tree",
    "Doing the dishes", "Drinking alcohol", "Drinking water", "Driving a car", "Eating hamburgers",
    "Feeding the pigeons", "Fighting as a knight", "Fishing on a lake", "Fixing a car engine",
    "Licking peanut butter off a knife", "Licking an ice cream", "Lighting a campfire",
    "Listening to music", "Doing homework", "Making toast", "Milking a cow", "Putting out the trash",
    "Reading a newspaper", "Repairing a bike", "Restarting a computer", "Rooting for someone",
    "Setting up a tent", "Sleepwalking", "Sleeping", "Spreading butter on toast",
    "Stopping for red lights", "Taking public transport", "Using a typewriter", "Washing your hands",
    "Watching a movie", "Watering plants", "Working overtime", "Writing a book", "Writing a speech",
]

RELATIONSHIPS = [
    "Criminal and lawyer", "Coworkers", "Brothers/sisters", "Old person and caretaker", "Divorced",
    "Just married", "New coworker", "Worker and boss", "Ambassador and royalty", "Royalty and servant",
    "Neighbours", "Music band members", "Parent/child", "Mortal enemies", "Bank teller and client",
    "Biker club gang members", "Mobster and Mafia boss", "Car mechanic and client", "Dance competitors",
    "Model and stylist", "Model and photographer", "Nurse and patient", "Doctor and patient",
    "Bar owner and regular", "Killer and victim", "Long lost friends", "Kindergartners",
    "College students", "Frathouse members", "Strikers/protesters", "Inspector and suspect",
    "Cousins", "Grandparent and grandchild",
]

JOBS = [
    "Accountant", "Acrobat", "Ambassador", "Archeologist", "Architect", "Artist", "Assassin",
    "Astronomer", "Attorney", "Author", "Baker", "Banker", "Barber", "Bartender", "Berserker",
    "Blacksmith", "Bookkeeper", "Brewmaster", "Bricklayer", "Builder", "Bus driver", "Businessperson",
    "Butcher", "Carpenter", "Cashier", "Chef", "Cleaner", "Co-pilot", "Coach", "Coalminer",
    "Composer", "Conquistador", "Coroner", "Dancer", "Dentist", "Designer", "Detective", "Developer",
    "Dietician", "Diplomat", "Dock worker", "Doctor", "Dog hairdresser", "Dog trainer", "Drug dealer",
    "Economist", "Editor", "Electrician", "Engineer", "Evil genius", "Exorcist", "Factory worker",
    "Farmer", "Filmmaker", "Firefighter", "Fisherman", "Flight attendant", "Florist", "Fortune teller",
    "Photo model", "Gardener", "Geologist", "Guru", "Gynecologist", "Hairdresser", "Harbormaster",
    "Hit man", "Horse tamer", "HR officer", "IT engineer", "Jeweler", "Journalist", "Judge",
    "Kitchen chef", "Lawyer", "Lecturer", "Librarian", "Lifeguard", "Machine operator", "Magician",
    "Manure collector", "Mechanic", "Model", "Musician", "Newsreader", "Nun", "Nurse", "Nutritionist",
    "Optician", "Orchestra director", "Painter", "Parking lot guard", "Pest controller", "Pharmacist",
    "Photographer", "Physician", "Piercer", "Pilot", "Pirate", "Plumber", "Police officer",
    "Police dog trainer", "Politician", "Postal worker", "Priest", "Programmer", "Psychologist",
    "Radar controller", "Real estate agent", "Receptionist", "Roman legion soldier", "Saint",
    "Salesperson", "Scientist", "Scuba diver", "Sea captain", "Secretary", "Security guard", "Shaman",
    "Shepherd", "Singer", "Smuggler", "Soldier", "Speech writer", "Stripper", "Surgeon", "Tailor",
    "Tank driver", "Tattoo artist", "Taxi driver", "Teacher", "Therapist", "Traffic warden",
    "Translator", "Travel agent", "Undertaker", "Veterinarian", "Videographer", "Voodoo priest",
    "Waiter/waitress", "Watch maker", "Welder", "Window cleaner", "Writer", "Visual merchandiser",
]

OBJECTS = [
    "Apple", "ATM machine", "Backpack", "Banana", "Beard", "Bed", "Bike", "Blindfold", "Bottle",
    "Briefcase", "Button", "Cactus", "Car", "Carpet", "Cash register", "Chair", "Chewing gum",
    "Cloud", "Coin", "Compass", "Cookbook", "Cooking pot", "Copper wire", "Cow", "Crown", "Dagger",
    "Diamond", "Dictionary", "Dress", "Driving license", "Drone", "Dust", "Earring", "Eyeball",
    "Fake money", "False teeth", "Fax machine", "Fishing rod", "Floor", "Glass", "Gloves", "Glue",
    "Goldfish", "Golden ring", "Guitar", "Guitar pick", "Hammer", "Harpoon", "Hat", "Hay stack",
    "Hearing aid", "Headphone", "Horse", "Ice cream", "Identity card", "Key", "Laptop", "Lava",
    "Library member card", "Lifting weights", "Light bulb", "Lighter", "Lipstick", "Magnifying glass",
    "Map", "Medal", "Medicine", "Microscope", "Milk", "Mirror", "Mud", "Mustache", "Nachos",
    "Necklace", "Newspaper", "Nose", "Painkiller", "Paper", "Passport", "Pen", "Pencil", "Pajamas",
    "Pizza", "Postcard", "Printer", "Purse", "Rainbow", "Record player", "Robot", "Rocket",
    "Rubber ducky", "Sandwich", "Scarf", "Scissors", "Set of cards", "Shield", "Sleeping bag",
    "Soccer ball", "Sofa", "Spear", "Stamp", "Statue", "Stone", "Stop sign", "Sunglasses", "Sunlight",
    "Sunscreen", "Sushi", "Sword", "Table", "Tape", "Telescope", "Tent", "Time bomb", "Toy",
    "Toothpick", "Tree", "Trophy", "Trumpet", "Ugly painting", "Umbrella", "Violin", "Walking cane",
    "Wallet", "Watch", "Watermelon", "Waterbed", "Xylophone", "Yogurt", "Zoo ticket",
]
